services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8000:8000"
        networks:
            - mynetwork
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        depends_on:
            - api
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge