FROM node:22-slim

WORKDIR /app

COPY ./package-lock.json /app/
COPY ./package.json /app/
RUN npm install

COPY app/ /app/app/
COPY ./.env.production /app/
COPY ./next.config.js /app/

RUN npm run build

EXPOSE 3000

ENTRYPOINT [ "npm", "start" ]
