services:
    api:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            - mynetwork
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - api
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge